"""empty message

Revision ID: 6b43fd068b29
Revises: 
Create Date: 2020-04-11 21:01:07.313873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b43fd068b29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=56), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('infotype_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('occupation', sa.String(length=128), nullable=True),
    sa.Column('email_id_1', sa.String(length=128), nullable=True),
    sa.Column('email_id_2', sa.String(length=128), nullable=True),
    sa.Column('phone_1', sa.String(length=128), nullable=True),
    sa.Column('phone_2', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_link', sa.String(length=256), nullable=False),
    sa.Column('source_link_valid', sa.Boolean(), nullable=True),
    sa.Column('details', sa.String(length=512), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['infotype_id'], ['info_type.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    op.drop_table('location')
    op.drop_table('info_type')
    # ### end Alembic commands ###
