"""Added clinics table.

Revision ID: 75d4b61ade14
Revises: 51fd5c8b1ee7
Create Date: 2020-04-14 04:16:58.590304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d4b61ade14'
down_revision = '51fd5c8b1ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fever_clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('point_of_contact', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('email_id_1', sa.String(length=128), nullable=True),
    sa.Column('email_id_2', sa.String(length=128), nullable=True),
    sa.Column('phone_1', sa.String(length=128), nullable=True),
    sa.Column('phone_2', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fever_clinics')
    # ### end Alembic commands ###
