"""empty message

Revision ID: a8ced954a3ec
Revises: 
Create Date: 2020-04-13 23:34:36.197312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ced954a3ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('email_id_1', sa.String(length=128), nullable=True),
    sa.Column('email_id_2', sa.String(length=128), nullable=True),
    sa.Column('phone_1', sa.String(length=128), nullable=True),
    sa.Column('phone_2', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('point_of_contact', sa.String(length=128), nullable=True),
    sa.Column('email_id_1', sa.String(length=128), nullable=True),
    sa.Column('email_id_2', sa.String(length=128), nullable=True),
    sa.Column('phone_1', sa.String(length=128), nullable=True),
    sa.Column('phone_2', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('point_of_contact', sa.String(length=128), nullable=True),
    sa.Column('email_id_1', sa.String(length=128), nullable=True),
    sa.Column('email_id_2', sa.String(length=128), nullable=True),
    sa.Column('phone_1', sa.String(length=128), nullable=True),
    sa.Column('phone_2', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratories')
    op.drop_table('hospitals')
    op.drop_table('doctors')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('category_list')
    # ### end Alembic commands ###
